# **NGC 6**

In [1]:
import numpy as np

In [2]:
A = np.array([[1, -1],
              [6, 4]])

In [3]:
B = np.array([1, 3])

In [4]:
print(A, B)

[[ 1 -1]
 [ 6  4]] [1 3]


In [6]:
T = A @ B
T

array([-2, 18])

In [7]:
T/B

array([-2.,  6.])

In [8]:
C = np.array([[1, 2],
              [2, 4]])

In [12]:
D = np.array([1, 2])

In [13]:
t = C @ D
t

array([ 5, 10])

In [16]:
5*D

array([ 5, 10])